export const categories = [
  { label: 'All Projects', count: 23 },
  { label: 'Architecture', count: 6 },
  { label: 'Urban Projects', count: 5 },
  { label: 'Interior Design', count: 7 },
  { label: 'Residences', count: 5 },
];

export const imagesByCategory = {
  'All Projects': [
    "/img-33.jpg",
    "/img-34.jpg",
    "/img-30.jpg",
    "/img-31.jpg",
    "/img-32.jpg",
    "/img-33.jpg",
    "/img-34.jpg",
    "/img-28.jpg",
    "/img-29.jpg",
    "/img-30.jpg",
    "/img-31.jpg",
    "/img-32.jpg",
    "/img-33.jpg",
    "/img-34.jpg",
    "/img-28.jpg",
    "/img-29.jpg",
    "/img-30.jpg",
    "/img-31.jpg",
    "/img-32.jpg",
    "/img-33.jpg",
    "/img-34.jpg",
    "/img-28.jpg"
  ],
  'Architecture': [ "/img-28.jpg",
    "/img-29.jpg",
    "/img-28.jpg",
    "/img-29.jpg",
    "/img-28.jpg",
    "/img-29.jpg" ],
  'Urban Projects': [ "/img-30.jpg",
    "/img-33.jpg",
    "/img-30.jpg",
    "/img-33.jpg",
    "/img-30.jpg" ],
  'Interior Design': [ "/img-31.jpg",
    "/img-32.jpg",
    "/img-31.jpg",
    "/img-32.jpg",
    "/img-31.jpg",
    "/img-32.jpg",
    "/img-31.jpg" ],
  'Residences': [ "/img-33.jpg",
    "/img-34.jpg",
    "/img-33.jpg",
    "/img-34.jpg",
    "/img-33.jpg" ],
};
